
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.2'

_lr_method = 'LALR'

_lr_signature = b'\xdb\xe2j`\xab\xd6[\xc5s\x16v}*^\xf3\xbf'
    
_lr_action_items = {'#':([2,],[5,]),'NAME':([0,4,5,6,7,12,13,16,17,],[2,2,9,10,11,14,15,18,19,]),'DELIM':([1,3,8,9,14,18,19,],[4,-2,-1,-6,-3,-4,-5,]),'-':([2,14,],[6,16,]),',':([2,15,],[7,17,]),'ANTI':([11,],[13,]),'ARROW':([10,],[12,]),'$end':([1,3,8,9,14,18,19,],[0,-2,-1,-6,-3,-4,-5,]),}

_lr_action = { }
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = { }
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'cnstrnts':([0,],[1,]),'def':([0,4,],[3,8,]),}

_lr_goto = { }
for _k, _v in _lr_goto_items.items():
   for _x,_y in zip(_v[0],_v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = { }
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> cnstrnts","S'",1,None,None,None),
  ('cnstrnts -> cnstrnts DELIM def','cnstrnts',3,'p_cnstrnts_recur','witnesscheck.py',118),
  ('cnstrnts -> def','cnstrnts',1,'p_cnstrnts_anchor','witnesscheck.py',123),
  ('def -> NAME - NAME ARROW NAME','def',5,'p_def_path','witnesscheck.py',128),
  ('def -> NAME - NAME ARROW NAME - NAME','def',7,'p_def_path','witnesscheck.py',129),
  ('def -> NAME , NAME ANTI NAME , NAME','def',7,'p_def_antivalence','witnesscheck.py',136),
  ('def -> NAME # NAME','def',3,'p_def_neq','witnesscheck.py',141),
]
